[package]
name = "counter"
description = "A simple counter example demonstrating state and button interaction."
version = "0.5.1"
publish = false
edition.workspace = true

[dependencies]
anyhow.workspace = true
gpui.workspace = true
gpui_platform.workspace = true
gpui-component = { workspace = true }

[lints]
workspace = true
